"""posts status


Revision ID: 3ed51f4ca7af
Revises: a8782df0fdf9
Create Date: 2025-09-17 01:54:53.068374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ed51f4ca7af'
down_revision: Union[str, Sequence[str], None] = 'a8782df0fdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('poststatus', sa.Enum('scheduled', 'published', name='poststatus'), nullable=True, native_enum=False))
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', postgresql.ENUM('scheduled', 'published', name='poststatus'), autoincrement=False, nullable=True))
    op.drop_column('posts', 'poststatus')
    # ### end Alembic commands ###
