"""postAnaltics and post table changed

Revision ID: 5e9b6c2f178a
Revises: 6eb2b42fcf9b
Create Date: 2025-09-16 15:24:37.751538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9b6c2f178a'
down_revision: Union[str, Sequence[str], None] = '6eb2b42fcf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
