"""posts and users table modified

Revision ID: a8782df0fdf9
Revises: 388a8307b73a
Create Date: 2025-09-17 01:46:36.052687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8782df0fdf9'
down_revision: Union[str, Sequence[str], None] = '388a8307b73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    poststatus = sa.Enum('scheduled', 'published', name='poststatus')
    poststatus.create(op.get_bind())
    op.add_column('posts', sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('status', sa.Enum('scheduled', 'published', name='poststatus'), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'status')
    poststatus.drop(op.get_bind())
    op.drop_column('posts', 'scheduled_time')
    # ### end Alembic commands ###
