"""posts status


Revision ID: be9104182cb4
Revises: 3ed51f4ca7af
Create Date: 2025-09-17 01:57:09.790384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be9104182cb4'
down_revision: Union[str, Sequence[str], None] = '3ed51f4ca7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.Enum('scheduled', 'published', name='poststatus', native_enum=False), nullable=True))
    op.drop_column('posts', 'poststatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('poststatus', postgresql.ENUM('scheduled', 'published', name='poststatus'), autoincrement=False, nullable=True))
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
