"""postAnaltics and post table changed

Revision ID: c5b89609efa4
Revises: fe2d4b0b16a7
Create Date: 2025-09-16 15:39:53.762918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b89609efa4'
down_revision: Union[str, Sequence[str], None] = 'fe2d4b0b16a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
